name: Daily Strategy Report

on:
  schedule:
    # 매일 한국 시간 오전 9시 (UTC 00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Email Library
        run: npm install nodemailer

      - name: Run Automation Script
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: node scripts/daily_automation.js