name: Daily Strategy Report

on:
  schedule:
    # 매일 UTC 05:00 실행 (유럽 CET 기준 오전 6시, 서머타임 시 7시)
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Email Library
        run: npm install nodemailer

      - name: Run Automation Script
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          # EMAIL_TO는 스크립트 내부에 하드코딩되었으므로 제거함
        run: node scripts/daily_automation.js
